"""
泰小虎智能体 - Prompt管理模块
"""

from .prompt_manager import PromptManager, get_prompt_manager
from .system_prompts import (
    SYSTEM_PROMPT,
    ORCHESTRATOR_PROMPT,
    SAFETY_GUARD_PROMPT,
    INTENT_ROUTER_PROMPT,
    PROFILE_EXTRACTOR_PROMPT,
    SYMPTOM_COLLECTOR_PROMPT,
    RECOMMENDATION_ENGINE_PROMPT,
    PRODUCT_CONSULT_PROMPT,
    KNOWLEDGE_QA_PROMPT,
    BOUNDARY_HANDLER_PROMPT,
    CUSTOMER_SERVICE_PROMPT,
    DISCLAIMER_PROMPT
)

__all__ = [
    'PromptManager',
    'get_prompt_manager',
    'SYSTEM_PROMPT',
    'ORCHESTRATOR_PROMPT',
    'SAFETY_GUARD_PROMPT',
    'INTENT_ROUTER_PROMPT',
    'PROFILE_EXTRACTOR_PROMPT',
    'SYMPTOM_COLLECTOR_PROMPT',
    'RECOMMENDATION_ENGINE_PROMPT',
    'PRODUCT_CONSULT_PROMPT',
    'KNOWLEDGE_QA_PROMPT',
    'BOUNDARY_HANDLER_PROMPT',
    'CUSTOMER_SERVICE_PROMPT',
    'DISCLAIMER_PROMPT'
]
